### ISSUE TITLE
Issue during the compilation of Pangolin

### ISSUE THREAD

**Issue by stephane-lb** [ahundt/ElasticFusion#1]
Hi Andrew,

Just back from holidays, got my laptop, and tried to launch the script.
I got this error, I have not investigated yet, and just in case you have an idea, this is the trace : 

```
> $ brew install pangolin                                           [±master ✓]
==> Installing pangolin from ahundt/robotics
==> Cloning https://github.com/stevenlovegrove/Pangolin.git
Updating /Library/Caches/Homebrew/pangolin--git
==> Checking out branch master
==> cmake -G Unix Makefiles .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAG
==> make
Last 15 lines from /Users/Saorel/Library/Logs/Homebrew/pangolin/02.make:
    PixelFormat     fmtdst;
    ^~~~~~~~~~~
    AVPixelFormat
/usr/local/include/libavutil/pixfmt.h:61:6: note: 'AVPixelFormat' declared here
enum AVPixelFormat {
     ^
[ 48%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/pvn_video.cpp.o
cd /tmp/pangolin20160801-12763-18vhex7/build/src && /usr/local/Library/ENV/4.3/clang++   -Dpangolin_EXPORTS -I/tmp/pangolin20160801-12763-18vhex7/include -I/tmp/pangolin20160801-12763-18vhex7/build/src/include -I/usr/local/include -I/usr/local/include/eigen3 -I/usr/include/python2.7 -I/usr/local/include/OpenEXR  -std=c++0x -Wall  -stdlib=libc++ -DNDEBUG -fPIC   -o CMakeFiles/pangolin.dir/video/drivers/pvn_video.cpp.o -c /tmp/pangolin20160801-12763-18vhex7/src/video/drivers/pvn_video.cpp
3 errors generated.
make[2]: *** [src/CMakeFiles/pangolin.dir/video/video_output.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
3 errors generated.
make[2]: *** [src/CMakeFiles/pangolin.dir/video/video.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/ahundt/homebrew-robotics/issues

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:353:in `open_http': 422 Unprocessable Entity (GitHub::Error)
Validation Failed
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:30:in `open'
    from /usr/local/Library/Homebrew/utils.rb:523:in `open'
    from /usr/local/Library/Homebrew/utils.rb:554:in `issues_matching'
    from /usr/local/Library/Homebrew/utils.rb:586:in `issues_for_formula'
    from /usr/local/Library/Homebrew/exceptions.rb:222:in `fetch_issues'
    from /usr/local/Library/Homebrew/exceptions.rb:218:in `issues'
    from /usr/local/Library/Homebrew/exceptions.rb:263:in `dump'
    from /usr/local/Library/brew.rb:132:in `rescue in <main>'
    from /usr/local/Library/brew.rb:28:in `<main>'
```

Have a great day !

Stephane

**Comment by ahundt** [comment]
@stephane-lb is this still a problem? Sorry I didn't see this earlier!
